name: Main

on:
  push

jobs:
  # Using pyinstaller
  build-python:
    name: Build Python (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            output_name: "linux"
          - os: windows-latest
            output_name: "win32.exe"
          - os: macos-latest
            output_name: "darwin"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/src/requirements.txt
      - name: Build executable
        run: |
          pyinstaller --onefile --name=${{ matrix.output_name }} --distpath=python/dist python/src/main.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output_name }}
          path: python/dist/${{ matrix.output_name }}

  build-node:
    runs-on: ubuntu-latest
    needs: build-python
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - name: Download Python Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: python/dist
          merge-multiple: true
      - run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: node
          path: dist